services:
  - type: web
    name: chatgpt-api
    env: python
    buildCommand: ""
    startCommand: "python app.py"
    envVars:
      - key: OPENAI_API_KEY
        value: sk-...  # (sau này bạn có thể để trống và add qua dashboard Render)
